/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Style from "@/styles/Home.module.css";
import { Container, Row, Col, Button, Table, Carousel } from "react-bootstrap";
import { useRouter } from "next/router";
import axios from "axios";
import { BASE_URL } from "@/utils/api";
import { useEffect, useState } from "react";
import { baseImgUrl } from "@/utils/imgUrl";
import Link from "next/link";



export default function RoomDetails() {

    const [data, setData] = useState([]);
    const [seats, setSeats] = useState([])
    const [loading, setLoading] = useState(false);

    const router = useRouter();
    const { roomID } = router.query;

    // console.log(roomID);

    useEffect( () =>{
      axios.get(BASE_URL + `/${roomID}/room_details` )
      .then((res) =>{
        setData(res?.data.data)
      })
    } ,[roomID])
    console.log(data)

    useEffect( () =>{
      axios.get(BASE_URL + `/${roomID}/seat_details` )
      .then(res =>{
        setSeats(res.data.data)
      })
    } , [roomID])
    console.log(seats)
  
  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` mt-5`}>
        <Container>
          <div
            style={{
              background: "#fff",
              padding: "25px 50px",
              borderRadius: "20px",
              marginBottom: "30px",
            }}
            className="shadow"
          >
            <Row>
              <Col md={6} sm={12}>
                <div>
                <Carousel className="">
      <Carousel.Item className="carousel-fade">

      {data?.image1 === null || data?.image1 === undefined  ? (
             <Image src="/fh.jpg" alt="" className="img-fluid custom-image" style={{height:"400px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image1} alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
        )} 

      
      </Carousel.Item>
      <Carousel.Item>
      {data?.image2 === null || data?.image2 === undefined ? (
             <Image src="/fh.jpg" alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image2} alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
        )} 
      </Carousel.Item>
      <Carousel.Item>
      {data?.image3 === null || data?.image3 === undefined ? (
             <Image src="/fh.jpg" alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image3} alt="" className="img-fluid " style={{height:"300px"}}  width={600} height={300} />
        )} 
      </Carousel.Item>
    </Carousel>
   
                </div>
                {/* <Image src="/fh.jpg" alt="" className="img-fluid" width={300} height={300} /> */}
                <div className="">
                  <h2> Video</h2>
                  <iframe
                    width="500"
                    height="315"
                    src={data?.youtube_link}
                    title="YouTube video player"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen
                  ></iframe>
                </div>
              </Col>
              <Col md={6} sm={12}>
                <div>
                  <div>
                    <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                      ভূতের বাড়ি 
                    </h4>
                    <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  </div>
                  <div className="des">
                    <p>
                     {data?.room_details}

                    </p>
                  </div>
                  <div className="border 1px solid p-4">
                    <h4>1st Floor; Flat no: A-02; Room no: 102</h4>
                    <div>
                      <img src="/status.png" alt="" className="img-fluid" />
                    </div>
                    <div className="d-flex mt-3">
                      {
                        seats?.map( (seat) => <div key={seat.id}>
                          <Link href={''}>
                          <button className="me-4 customButton">{seat?.seat_name}</button>
                          </Link>
                        </div>)
                      }
                     
                      {/* <button className="me-4 customButton">102-B</button>
                      <button className="me-4 customButton">102-C</button>
                      <button className="customButton">102-D</button> */}
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </>
  );
}
