/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Style from "@/styles/Home.module.css";
import { Container, Row, Col, Button, Table, Carousel } from "react-bootstrap";
import { useRouter } from "next/router";
import axios from "axios";
import { BASE_URL } from "@/utils/api";
import { useEffect, useState } from "react";
import { baseImgUrl } from "@/utils/imgUrl";
import Link from "next/link";
import Swal from "sweetalert2";
import Cookies from "js-cookie";



export default function RoomDetails() {

    const [data, setData] = useState([]);
    const [seats, setSeats] = useState([])
    const [loading, setLoading] = useState(false);
    const [token, setToken] = useState(null);
   

    const router = useRouter();
    const { roomID } = router.query;

    // console.log(roomID);

    useEffect( () =>{
      axios.get(BASE_URL + `/${roomID}/room_details` )
      .then((res) =>{
        setData(res?.data.data)
      })
    } ,[roomID])
    console.log(data)

    useEffect( () =>{
      axios.get(BASE_URL + `/${roomID}/seat_details` )
      .then(res =>{
        setSeats(res.data.data)
      })
    } , [roomID])
    console.log(seats)

    useEffect(() => {
      const storedCookies = Cookies.get("TOKEN_LOGIN");
      setToken(storedCookies);
    }, []);
    console.log(token)

    const handelBooking = async (seat_id) => {
      try {
        const result = await Swal.fire({
          title: "Are you sure?",
          text: "You want to book the seat",
          icon: "warning",
          showCancelButton: true,
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Sure!",
        });
    
        if (result.isConfirmed) {
          const requestBody = {
            seat_id : seat_id,
          };
          console.log(seat_id);
          const response = await axios.post(BASE_URL + `/booking_seat`, requestBody, {
            headers: {
              booking_token: token,
            },
          });
          console.log(response.data);
    
          if (response.data.status === "success") {
            Swal.fire({
              title: `${response.data.messsage}`,
              text: "Your seat is booked.",
              icon: "success",
            });
          } else {
            Swal.fire({
              title: "Booking Failed",
              text: "There was an issue booking the seat.",
              icon: "error",
            });
          }
    
          console.log("booked");
        }
      } catch (error) {
        // Handle the error
        console.error("Error booking seat:", error);
        Swal.fire({
          title: "Please Login",
          text: "Please Login And Try To Booked",
          icon: "error",
        });
      }
    };
    

  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` mt-5`}>
        <Container>
          <div
            style={{
              background: "#fff",
              padding: "25px 50px",
              borderRadius: "20px",
              marginBottom: "30px",
            }}
            className="shadow"
          >
            <Row>
              <Col md={6} sm={12}>
                <div>
                <Carousel className="">
      <Carousel.Item className="carousel-fade">

      {data?.image1 === null || data?.image1 === undefined  ? (
             <Image src="/fh.jpg" alt="" className="img-fluid custom-image" style={{height:"400px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image1} alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
        )} 

      
      </Carousel.Item>
      <Carousel.Item>
      {data?.image2 === null || data?.image2 === undefined ? (
             <Image src="/fh.jpg" alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image2} alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
        )} 
      </Carousel.Item>
      <Carousel.Item>
      {data?.image3 === null || data?.image3 === undefined ? (
             <Image src="/fh.jpg" alt="" className="img-fluid " style={{height:"300px"}} width={600} height={300} />
           
        ) : ( 
          <Image src={baseImgUrl + data?.image3} alt="" className="img-fluid " style={{height:"300px"}}  width={600} height={300} />
        )} 
      </Carousel.Item>
    </Carousel>
   
                </div>
                {/* <Image src="/fh.jpg" alt="" className="img-fluid" width={300} height={300} /> */}
                <div className="">
                  <h2> Video</h2>
                  <iframe
                    width="500"
                    height="315"
                    src={data?.youtube_link}
                    title="YouTube video player"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen
                  ></iframe>
                </div>
              </Col>
              <Col md={6} sm={12}>
                <div>
                  <div>
                    <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                      ভূতের বাড়ি 
                    </h4>
                    <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  </div>
                  <div className="des">
                    <p>
                     {data?.room_details}

                    </p>
                  </div>
                  <div className="border 1px solid p-4">
                    <h4>1st Floor; Flat no: A-02; Room no: 102</h4>
                    <div>
                      <img src="/status.png" alt="" className="img-fluid" />
                    </div>
                    <div className="d-flex mt-3">
                      {
                        seats?.map( (seat) => <div key={seat.id}>
                          <div onClick={() => handelBooking(seat.id)}>
                          <button className="me-4 customButton">{seat?.seat_name}</button>
                          </div>
                        </div>)
                      }
                     
                      {/* <button className="me-4 customButton">102-B</button>
                      <button className="me-4 customButton">102-C</button>
                      <button className="customButton">102-D</button> */}
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </>
  );
}
