import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Style from "@/styles/Home.module.css";
import { BASE_URL } from "@/utils/api";
import { Container, Row, Col, Button, Table } from "react-bootstrap";
import { useRouter } from "next/router";
import axios from "axios";
import Link from "next/link";

export default function BuildingDetails() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const router = useRouter();
  const { buildingID } = router.query;
  console.log(buildingID);

  useEffect(() => {
    axios.get(BASE_URL + `/${buildingID}/room_view`).then((response) => {
      setData(response?.data);
    });
  }, [buildingID]);

  console.log(data);

  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-5 min-vh-100">
        <Container>
          <div
            style={{
              background: "#fff",
              padding: "10px 10px",
              borderRadius: "20px",
              marginBottom: "30px",
            }}
            className="shadow"
          >
            <div></div>
            <Row>
              <Col md={12}>
                <Table className="mt-4" striped bordered hover responsive>
                  <thead>
                    <tr>
                      <th>Building Name</th>
                      <th>Floor</th>
                      <th>Flat No.</th>
                      <th>Room No.</th>
                      <th>Total Seat</th>
                      <th>View Details</th>
                    </tr>
                  </thead>

                  <tbody>
                    {data?.data?.map((item, index) => (
                      <tr key={index}>
                        <td>{item.building_name}</td>
                        <td>{item.floor_name}</td>
                        <td>{item.flat_name}</td>
                        <td>{item.room_name}</td>
                        <td>{item.total}</td>
                        <td>
                          <Link
                            href={`/room-details/${item.room_id}`}
                            className="d-flex justify-content-center text-decoration-none"
                          >
                            <Button className="py-1 px-3">বিস্তারিত</Button>
                          </Link>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </>
  );
}
