/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Style from "@/styles/Home.module.css";
import { Container, Row, Col, Button, Table } from "react-bootstrap";

export default function ConfirmSeat() {
  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` mt-5`}>
        <Container>
          <div
            style={{
              background: "#fff",
              padding: "25px 50px",
              borderRadius: "20px",
              marginBottom: "30px",
            }}
            className="shadow"
          >
            <Row>
              <Col md={6} sm={12}>
                <Image src="/fh.jpg" alt="" className="img-fluid" />
                <div className="py-4">
                  <h2>Our youtube Video</h2>
                  <iframe
                    width="480"
                    height="315"
                    src="https://www.youtube.com/embed/aDOJMB3TKfk?si=TJu0amFmtMSnDVg4"
                    title="YouTube video player"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen
                  ></iframe>
                </div>
              </Col>
              <Col md={6} sm={12}>
                <div>
                  <div>
                    <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                      ভূতের বাড়ি
                    </h4>
                    <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  </div>
                  <div className="des">
                    <p>
                      Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                      Nobis libero cupiditate sapiente adipisci iure doloremque
                      corporis perferendis pariatur ex consequatur recusandae
                      voluptatibus, quod itaque officiis eos veritatis sequi
                      quaerat fugiat?
                    </p>
                  </div>
                  <div className="border 1px solid p-4">
                    <h4>1st Floor; Flat no: A-02; Room no: 102</h4>
                    <div>
                      <img src="/status.png" alt="" className="img-fluid" />
                    </div>
                    <div className="d-flex mt-3">
                      <button className="me-4 customButton">102-A</button>
                      <button className="me-4 customButton">102-B</button>
                      <button className="me-4 customButton">102-C</button>
                      <button className="customButton">102-D</button>
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </>
  );
}
