import Head from "next/head";
import Image from "next/image";
import Style from "@/styles/Home.module.css";
import { Container, Row, Col, Button, Table } from "react-bootstrap";

export default function HostelDetails() {
  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` mt-5`}>
        <Container>
          <div
            style={{
              background: "#fff",
              padding: "25px 50px",
              borderRadius: "20px",
              marginBottom: "30px",
            }}
            className="shadow"
          >
            <div>
              <h4 style={{ fontSize: "20px", fontWeight: 700 }}>ভূতের বাড়ি</h4>
              <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
            </div>
            <Row>
              <Col md={12}>
                <Table className="mt-3" striped bordered hover>
                  <thead>
                    <tr>
                      <th>Floor</th>
                      <th>Flat No.</th>
                      <th>Room No.</th>
                      <th>Total Seat</th>
                      <th>Available Seat</th>
                      <th>View Details</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                    <tr>
                      <td>1st Floor</td>
                      <td>A-01</td>
                      <td>101</td>
                      <td>03</td>
                      <td>02</td>
                      <td>
                        <Button>View</Button>
                      </td>
                    </tr>
                  </tbody>
                </Table>
              </Col>
            </Row>
          </div>
        </Container>
      </main>
    </>
  );
}
